version: '2'
services:
    la_librairie_de_raymonde-app:
        image: la_librairie_de_raymonde
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://la_librairie_de_raymonde-postgresql:5432/la_librairie_de_raymonde
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    la_librairie_de_raymonde-postgresql:
        extends:
            file: postgresql.yml
            service: la_librairie_de_raymonde-postgresql
